service: github-animated-status

plugins:
  modules:
    - serverless-webpack

provider:
  name: aws
  runtime: nodejs18.x

functions:
  update:
    handler: handler.update
    events:
      - schedule: cron(0 12 * * ? *)
